projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - api
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-1
        apiId: 2odsnpewp5hpfolrxplnl6ffeu
        frontend: javascript
        framework: react-native
        maxDepth: 2
extensions:
  amplify:
    version: 3
